# Generated by Django 6.0.7 on 2026-07-20 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(default='', max_length=512)),
                ('source_url', models.URLField(blank=True, default='', max_length=2048)),
                ('track', models.CharField(choices=[('content', 'Content Analysis'), ('visual', 'Visual / Motion Analysis'), ('full', 'Full Analysis')], default='content', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=16)),
                ('whisper_model', models.CharField(default='base', max_length=64)),
                ('gemini_model', models.CharField(default='gemini-2.5-flash', max_length=64)),
                ('gemma_model', models.CharField(default='gemma-4-31b-it', max_length=64)),
                ('transcript', models.TextField(blank=True, default='')),
                ('analysis_json', models.TextField(blank=True, default='')),
                ('visual_json', models.TextField(blank=True, default='')),
                ('design_json', models.TextField(blank=True, default='')),
                ('planner_markdown', models.TextField(blank=True, default='')),
                ('frames_extracted', models.IntegerField(default=0)),
                ('scenes_analysed', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Analysis Job',
                'ordering': ['-created_at'],
            },
        ),
    ]
